=== MichalMed/otevrene-formalni-normy/časová-platnost/draft/schémata/časová-platnost.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://ofn.gov.cz/vstupné/draft/schémata/časová-platnost.json",
    "type": "array",
    "title": "Časová platnost",
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "Časová platnost",
        "properties": {
            
            "vznik_časové_platnosti": {
                "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
            },
            "ukončení_časové_platnosti": {
                "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
            },
            "poslední_změna_platnosti": {
                "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
            },
            "časový_interval": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-interval.json"
                }
	    },
            "časová_opakovatelnost": {
                "type": "array",
                "items": {
                    "type": "string"
                }
	    }
        }
    }
}

=== MichalMed/otevrene-formalni-normy/časová-platnost/draft/příklady/1.json
[{
    "vznik_časové_platnosti": {
        "datum_a_čas": "2019-09-20T09:30:00"
    },
    "ukončení_časové_platnosti": {
        "datum_a_čas": "2019-01-22T09:30:00"
    },
    "poslední_změna_platnosti": {
		"datum_a_čas": "2019-01-23T09:30:00"
    },
    "časový_interval": [{
        "začátek": {
            "datum_a_čas": "2019-09-24T09:30:00+02:00"
        },
        "konec": {
            "datum_a_čas": "2019-09-28T09:30:00+02:00"
        }
    }, {
        "začátek": {
            "datum_a_čas": "2019-10-24T09:30:00+02:00"
        },
        "konec": {
            "datum_a_čas": "2019-11-28T09:30:00+02:00"
        }
    }],
    "časová_opakovatelnost": [
	"každý rok",
      	"každé století"
    ]
}]
