=== MichalMed/otevrene-formalni-normy/turistické-cíle/draft/schémata/turisticky_cil.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://ofn.gov.cz/aktuality/draft/schémata/turistický-cíl.json",
    "type": "array",
    "title": "Turistický cíl",
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "Turistický cíl",
        "properties": {
            "iri": {
                "$id": "#/items/properties/id",
                "type": "string",
                "format": "iri",
                "title": "Identifikátor",
                "description": "Unikátní identifikátor v podobě URL",
                "examples": [
                    "https://www.spilberk.cz/"
                ]
            },
            "název": {
                "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
            },
            "popis": {
                "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
            },
            "obrázek": {
                    "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/url.json"
            },
            "kouření": {
                    "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/boolean.json"
            },
            "přístupnost pro veřejnost": {
                    "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/boolean.json"
            },
              "kapacita": {
                    "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/celé-číslo.json"
            },          
            "vlastník": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
                }
            },
            "provozovatel": {
                    "$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
            },
            "umístění": {
                    "$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/umístění.json"
            },
            "kontakt": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/kontakty/draft/schémata/kontakt.json"
                }
            },
            "vstupné": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/vstupné/draft/schémata/vstupné.json"
                }
            },
            "otevírací_doba": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/otevírací-doba/draft/schémata/otevírací-doba.json"
                }
            },
            "bezbariérovost": {
                "$ref": "https://ofn.gov.cz/bezbariérovost/draft/schémata/bezbariérovost.json"
            },
            "jazyk": {
                "type": "array",
                "items": {
                    "$id": "#/items/properties/jazyk/items",
                    "type": "object", 
                    "title": "Jazyk",
                    "description": "Dostupný jazyk", 
                    "properties": {
                        "kód": {
                            "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
                        },
                        "název": {
                            "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
                        }
                    }    
                }
            },             
            "typ turistického cíle": {
                "type": "array",
                "items": {
                    "$id": "#/items/properties/typ-turistického-cíle/items",
                    "type": "object",
                    "title": "Typ turistického cíle",
                    "description": "Kategorizace turistického cíle",
                    "properties": {
                        "název": {
                            "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
                        }
                    }
                }
            }
        }
    }
}

=== MichalMed/otevrene-formalni-normy/turistické-cíle/draft/příklady/turisticky_cil_min.json
[{
    "iri": "https://www.spilberk.cz/",
    "název": {
        "cs": "Hrad Špilberk"
    },
    "umístění": {
        "geometrie": {
            "type": "Point",
            "coordinates": [16.5995939, 49.1944522]
        },
        "adresa": {
            "iri_adresního_místa": "https://linked.cuzk.cz/resource/ruian/adresni-misto/19095732"
        }
    },
    "vstupné": [{
        "název": {
            "cs": "Základní vstupné"
        },
        "podmínka": {
            "cs": "Občané, kteří nevyuživají slevy(ZTP, studenti)."
        },
        "částka": {
            "výše": 199,
            "měna": "CZK"
        }
    }, {
        "název": {
            "cs": "Studentské"
        },
        "podmínka": {
            "cs": "Po předložení průkazu ISIC"
        },
        "částka": {
            "výše": 99,
            "měna": "CZK"
        }
    }],
        "otevírací_doba": [{
	        "název": "letní",
	        "popis": "od května do října",
	        "od": "9:00",
	        "do": "17:00",
	        "časová platnost": "květen, červen, červenec, srpen, září, říjen"
    }]
}]

=== MichalMed/otevrene-formalni-normy/turistické-cíle/draft/příklady/1.json
[{
    "iri": "https://www.spilberk.cz/",
    "název": {
        "cs": "Hrad Špilberk",
        "en": "Špilberk Castle"
    },
    "umístění": {
        "geometrie": {
            "type": "Point",
            "coordinates": [16.5995939, 49.1944522]
        },
        "adresa": {
            "iri_adresního_místa": "https://linked.cuzk.cz/resource/ruian/adresni-misto/19095732"
        }
    },
    "vstupné": [{
        "název": {
            "cs": "Základní vstupné",
            "en": "Basic admission"
        },
        "podmínka": {
            "cs": "Občané, kteří nevyuživají slevy(ZTP, studenti).",
            "en": "People who don´t benefit from discounts (students, ...)."
        },
        "částka": {
            "výše": 199,
            "měna": "CZK"
        }
    }, {
        "název": {
            "cs": "Studentské",
            "en": "Student"
        },
        "podmínka": {
            "cs": "Po předložení průkazu ISIC.",
            "en": "Valid after presenting the ISIC card."
        },
        "částka": {
            "výše": 99,
            "měna": "CZK"
        }
    }],
    "otevírací_doba": [{
        "název": {
            "cs": "Letní otevírací doba",
            "en": "Summer opening hours"
        },
        "popis": {
            "cs": "Letní otevírací doba platí vždy od 1.5. do 31.10.",
            "en": "Summer opening hours begins on the 1st May and lasts till 31st of October."
        },
        "od": "2018-05-01",
        "do": "2019-10-31",
        "čas": [{
            "začátek": {
                "čas": "08:00:00"
            },
            "konec": {
                "čas": "12:00:00"
            }
        }, {
            "začátek": {
                "čas": "12:30:00"
            },
            "konec": {
                "čas": "17:30:00"
            }
        }],
        "den-v-týdnu": [{
            "iri": "https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/úterý",
            "iri": "https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/středa",
            "iri": "https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/čtvrtek", 
            "iri": "https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pátek"  
        }] 
    }]
}]

=== MichalMed/otevrene-formalni-normy/turistické-cíle/draft/příklady/turistický_cíl_min.json
[{
    "iri": "https://www.spilberk.cz/",
    "název": {
        "cs": "Hrad Špilberk",
        "en": "Špilberk Castle"
    },
    "umístění": {
        "geometrie": {
            "type": "Point",
            "coordinates": [16.5995939, 49.1944522]
        },
        "adresa": {
            "iri_adresního_místa": "https://linked.cuzk.cz/resource/ruian/adresni-misto/19095732"
        }
    },
    "vstupné": [{
        "název": {
            "cs": "Základní vstupné",
            "en": "Basic admission"
        },
        "podmínka": {
            "cs": "Občané, kteří nevyuživají slevy(ZTP, studenti).",
            "en": "People who don´t benefit from discounts (students, ...)."
        },
        "částka": {
            "výše": 199,
            "měna": "CZK"
        }
    }, {
        "název": {
            "cs": "Studentské",
            "en": "Student"
        },
        "podmínka": {
            "cs": "Po předložení průkazu ISIC.",
            "en": "Valid after presenting the ISIC card."
        },
        "částka": {
            "výše": 99,
            "měna": "CZK"
        }
    }],
        "otevírací_doba": [{
	        "název": "letní",
	        "popis": "od května do října",
	        "od": "9:00",
	        "do": "17:00",
	        "časová platnost": "květen, červen, červenec, srpen, září, říjen"
    }]
}]
