=== MichalMed/otevrene-formalni-normy/akce/draft/schémata/akce.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://ofn.gov.cz/akce/draft/schémata/akce.json",
    "type": "array",
    "title": "Akce",
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "Akce",
        "properties": {
            "iri": {
                "$id": "#/items/properties/id",
                "type": "string",
                "format": "iri",
                "title": "Identifikátor",
                "description": "",
                "examples": [
                    "https://brno.cz/zdroj/akce/abcd"
                ]
            },
            "název": {
                "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
            },
            "popis": {
                "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
            },
            "obrázek": {
                "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/url.json"
            },
            "pořadatel": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
                }
            },
            "hlavní_sponzor": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
                }
            },
            "sponzor": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
                }
            },
            "mediální_partner": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
                }
            },
            "umístění": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/umístění/draft/schémata/umístění.json"
                }
            },
            "trvání": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-interval.json"
                }
            },
            "kontakt": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/kontakty/draft/schémata/kontakt.json"
                }
            },
            "vstupné": {
                "type": "array",
                "items": {
                    "$ref": "https://ofn.gov.cz/vstupné/draft/schémata/vstupné.json"
                }
            }
        }
    }
}

=== MichalMed/otevrene-formalni-normy/akce/draft/příklady/1.json
[{
    "iri": "https://brno.cz/vinobraní/2019",
    "název": {
        "cs": "Brněnské vinobraní"
    },
    "popis": {
        "cs": "Město Brno Vás zve na již 21. vinobraní."
    },
    "obrázek": "https://brno.cz/vinobrani.jpg",
    "pořadatel": [{
        "osoba": {
            "ičo": "44992785",
            "název": "Statutární město Brno"
        }
    }],
    "hlavní_sponzor": [{
        "osoba": {
            "ičo": "44992785",
            "název": "Vinařství Vinam"
        }
    }],
    "sponzor": [{
        "osoba": {
            "ičo": "35922742",
            "název": "Vinařství Znovín"
        },
        "osoba": {
            "ičo": "65885514",
            "název": "Vinařství Valtice"
        }
    }],
    "mediální_partner": [{
        "osoba": {
            "ičo": "56485227",
            "název": "Brněnský denník"
        }
    }],
    "umístění": [{
        "geometrie": {
            "type": "Point",
            "coordinates": [15.9915114, 48.8566829]
        },
        "adresa": {
            "iri_adresního_místa": "https://linked.cuzk.cz/resource/ruian/adresni-misto/16135661"
        }
    }],
    "trvání": [{
        "začátek": {
            "datum_a_čas": "2019-01-01T09:30:00+02:00"
        },
        "konec": {
            "datum_a_čas": "2019-01-07T18:00:00+02:00"
        }
    }, {
        "začátek": {
            "datum_a_čas": "2019-01-14T09:30:00+02:00"
        },
        "konec": {
            "datum_a_čas": "2019-01-20T18:00:00+02:00"
        }
    }],
    "kontakt": [{
        "email": "akce@brno.cz",
        "mobil": "+420123456789",
        "facebook": "ChytreBrno",
        "instagram": "chytrebrno",
        "twitter": "chytrebrno",
        "url": "https://data.brno.cz"
    }],
    "vstupné": [{
        "název": {
            "cs": "Pro dospělé ve vybrané dny a časy"
        },
        "podmínka": {
            "cs": "Občané starší 18 let, kteří nevyuživají slevy(ZTP, studenti)."
        },
        "časová_platnost": [{
            "začátek": {
                "datum_a_čas": "2019-01-01T09:30:00+02:00"
        },
            "konec": {
                "datum_a_čas": "2019-01-05T18:00:00+02:00"
        }
    }, {
            "začátek": {
                "datum_a_čas": "2019-01-14T09:30:00+02:00"
        },
            "konec": {
                "datum_a_čas": "2019-01-19T18:00:00+02:00"
        }
    }],
        "částka": {
            "výše": 219.90,
            "měna": "CZK"
        }
    }, {
        "název": {
            "cs": "Pro děti"
        },
        "podmínka": {
            "cs": "Občané mladší 18 let"
        },
        "částka": {
            "výše": 180.90,
            "měna": "CZK"
        }
    }]
}]
