=== MichalMed/otevrene-formalni-normy/časová-specifikace/draft/schémata/časová-specifikace.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://ofn.gov.cz/časová-specifikace/draft/schémata/časová-specifikace.json",
	"type": "object",
	"title": "Časová specifikace",
	"required": ["typ"],
	"properties": {
		"typ": {
			"const": "Časová specifikace"
		},
		"iri": {

			"type": "string",
			"format": "iri",
			"title": "Identifikátor",
			"examples": [
				"https://www.trebic.cz/zdroj/aktualita/2020/dopadení-lupiče-na-francouzské-ulici"
			]
		},
		"název": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
		},
		"popis": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
		},
		"vytvořeno": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
		},
		"relevantní_do": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
		},
		"zneplatněno": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
		},
		"příloha": {
			"$ref": "https://ofn.gov.cz/přílohy/draft/schémata/přílohy.json"
		},
		"počet_opakování": {

			"type": "integer",
			"title": "Počet opakování",
			"examples": [
				3
			]
		},
		"časový_interval": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-interval.json"
		},
		"jiná_časová_specifikace": {

			"type": "array",
			"items": {
				"type": "string",
				"format": "iri",
				"pattern": "^https\\:\/\/data\\.mvcr\\.gov\\.cz\/zdroj\/číselníky\/jiná-časová-specifikace\/položky\/.*$",
				"title": "Jiná časová specifikace",
				"examples": [
					"https://data.mvcr.gov.cz/zdroj/číselníky/jiná-časová-specifikace/položky/dobré-počasí"
				]
			}
		},
		"den_v_týdnu": {

			"type": "array",
			"items": {
				"type": "string",
				"format": "iri",
				"pattern": "^https\\:\/\/data\\.mvcr\\.gov\\.cz\/zdroj\/číselníky\/dny-v-týdnu\/položky\/.*$",
				"title": "Den v týdnu",
				"examples": [
					"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pondělí"
				]
			}
		},
		"časová_doba": {

			"type": "array",
			"items": {
				"type": "string",
				"format": "iri",
				"pattern": "^http\\:\/\/publications\\.europa\\.eu\/resource\/authority\/timeperiod\/.*$",
				"title": "Časová doba",
				"examples": [
					"http://publications.europa.eu/resource/authority/timeperiod/OCT"
				]
			}
		},
		"frekvence": {

			"type": "array",
			"items": {
				"type": "string",
				"format": "iri",
				"pattern": "^http\\:\/\/publications\\.europa\\.eu\/resource\/authority\/frequency\/.*$",
				"title": "Frekvence",
				"examples": [
					"http://publications.europa.eu/resource/authority/frequency/BIWEEKLY"
				]
			}
		},
		"specifická_frekvence": {

			"type": "array",
			"title": "Specifická frekvence",
			"items": {

				"type": "object",
				"title": "Specifická frekvence",
				"required": ["typ"],
				"properties": {
					"typ": {

						"const": "Specifická frekvence"
					},
					"minuta": {

						"type": "integer",
						"title": "Minuta",
						"examples": [
							20
						]
					},
					"hodina": {

						"type": "integer",
						"title": "Hodina",
						"examples": [
							20
						]
					},
					"den_v_měsíci": {

						"type": "integer",
						"title": "Den v měsíci",
						"examples": [
							20
						]
					},
					"týden_v_měsíci": {

						"type": "integer",
						"title": "Týden v měsíci",
						"examples": [
							2
						]
					},
					"týden_v_roku": {

						"type": "integer",
						"title": "Týden v roku",
						"examples": [
							20
						]
					},
					"rok_v_desetiletí": {

						"type": "integer",
						"title": "Týden v měsíci",
						"examples": [
							2
						]

					},
					"rok_ve_století": {

						"type": "integer",
						"title": "Rok ve století",
						"examples": [
							20
						]
					}
				}
			}
		},
		"výjimka": {
			"$ref": "https://ofn.gov.cz/časová-specifikace/draft/schémata/seznam-časových-specifikací.json"
		},
		"časová_platnost": {
			"$ref": "https://ofn.gov.cz/časová-specifikace/draft/schémata/seznam-časových-specifikací.json"
		}
	}
}

=== MichalMed/otevrene-formalni-normy/časová-specifikace/draft/příklady/7.json
{
	"typ": "Časová specifikace",
	"časový_interval": {
		"typ": "Časový interval",
		"začátek": {
			"typ": "Časový okamžik",
			"datum_a_čas": "2020-01-01T00:00:01"
		},
		"konec": {
			"typ": "Časový okamžik",
			"datum_a_čas": "2021-12-31T23:59:59"
		}
	},
	"frekvence": [
		"http://publications.europa.eu/resource/authority/frequency/BIWEEKLY"
	],
	"den_v_týdnu": [
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pondělí"
	],
	"časová_doba": [
		"http://publications.europa.eu/resource/authority/timeperiod/OCT"
	]
}
