=== MichalMed/otevrene-formalni-normy/kontakty/draft/schémata/kontakt.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:kontakt="https://ofn.gov.cz/kontakty/" xmlns:základ="https://ofn.gov.cz/základní-datové-typy/" xmlns:věc="https://ofn.gov.cz/věc/" xmlns:umístění="https://ofn.gov.cz/umístění/" targetNamespace="https://ofn.gov.cz/kontakty/" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="https://ofn.gov.cz/základní-datové-typy/" schemaLocation="https://ofn.gov.cz/základní-datové-typy/draft/schémata/základní-datové-typy.xsd"/>
	<xs:import namespace="https://ofn.gov.cz/umístění/" schemaLocation="https://ofn.gov.cz/umístění/draft/schémata/umístění.xsd"/>
	<xs:import namespace="https://ofn.gov.cz/věc/" schemaLocation="https://ofn.gov.cz/věc/draft/schémata/věc.xsd"/>
	<xs:complexType name="kontakt">
		<xs:complexContent>
			<xs:extension base="věc:věc">
				<xs:sequence minOccurs="0" maxOccurs="1">
					<xs:element name="druh" type="základ:text" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="email" type="xs:string" minOccurs="0"/>
					<xs:element name="facebook" type="xs:string" minOccurs="0"/>
					<xs:element name="idds" type="xs:string" minOccurs="0"/>
					<xs:element name="instagram" type="xs:string" minOccurs="0"/>
					<xs:element name="mobil" type="xs:string" minOccurs="0"/>
					<xs:element name="telefon" type="xs:string" minOccurs="0"/>
					<xs:element name="twitter" type="xs:string" minOccurs="0"/>
					<xs:element name="url" type="xs:anyURI" minOccurs="0"/>
					<xs:element name="umístění" type="umístění:umístění" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="kontakt" type="kontakt:kontakt"/>
</xs:schema>

=== MichalMed/otevrene-formalni-normy/kontakty/draft/příklady/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<kontakt:kontakt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:kontakt="https://ofn.gov.cz/kontakty/"
xmlns:x="https://příklad.cz"
xmlns:umístění="https://ofn.gov.cz/umístění/"
xsi:schemaLocation="https://ofn.gov.cz/kontakty/ https://ofn.gov.cz/kontakty/draft/schémata/kontakt.xsd">
    <kontakt:druh xml:lang="cs">Neformální</kontakt:druh>
    <kontakt:druh xml:lang="en">Informal</kontakt:druh>
    <kontakt:email>otevrenadata@mvcr.cz</kontakt:email>
    <kontakt:idds>abcdef</kontakt:idds>
    <kontakt:mobil>+420123456789</kontakt:mobil>
    <kontakt:telefon>+420123456789</kontakt:telefon>
    <kontakt:url>https://data.gov.cz</kontakt:url>
    <kontakt:umístění>
        <umístění:adresa>
            <adresa:iri_adresního_místa>https://linked.cuzk.cz/resource/ruian/adresni-misto/16135661</adresa:iri_adresního_místa>
        </umístění:adresa>
    </kontakt:umístění> 
</kontakt:kontakt>
