=== MichalMed/otevrene-formalni-normy/události/draft/schémata/událost.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://ofn.gov.cz/události/draft/schémata/událost.json",
	"type": "object",
	"title": "Událost",
	"properties": {
		"iri": {
			"$id": "#/properties/iri",
			"type": "string",
			"format": "iri",
			"title": "Identifikátor",
			"examples": [
				"https://www.trebic.cz/zdroj/aktualita/2020/dopadení-lupiče-na-francouzské-ulici"
			]
		},
		"název": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
		},
		"popis": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
		},
		"vytvořeno": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
		},
		"relevantní_do": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
		},
		"zneplatněno": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
		},
		"příloha": {
			"$ref": "https://ofn.gov.cz/přílohy/draft/schémata/přílohy.json"
		},
		"dlouhý_popis": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
		},
		"vhodné_pro_děti": {
			"$id": "#/properties/vhodné_pro_děti",
			"type": "boolean",
			"title": "Vhodné pro děti",
			"examples": true
		},
		"vhodné_pro_zvířata": {
			"$id": "#/properties/vhodné_pro_zvířata",
			"type": "boolean",
			"title": "Vhodné pro zvířata",
			"examples": true
		},
		"registrace": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
		},
		"pořadatel": {
			"type": "array",
			"items": {
				"$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
			}
		},
		"hlavní_sponzor": {
			"type": "array",
			"items": {
				"$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
			}
		},
		"sponzor": {
			"type": "array",
			"items": {
				"$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
			}
		},
		"mediální_partner": {
			"type": "array",
			"items": {
				"$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
			}
		},
		"záštita": {
			"type": "array",
			"items": {
				"$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
			}
		},
		"umístění": {
			"type": "array",
			"items": {
				"$ref": "https://ofn.gov.cz/umístění/draft/schémata/umístění.json"
			}
		},
		"typ": {
			"type": "array",
			"items": {
				"id": "#/properties/typ/items/typ",
				"type": "string",
				"format": "iri",
				"title": "Typ",
				"examples": [
					"https://data.mvcr.gov.cz/zdroj/číselníky/typy-událostí/položky/muzikál"
				]
			}
		},
		"téma": {
			"type": "array",
			"items": {
				"id": "#/properties/téma/items/téma",
				"type": "string",
				"format": "iri",
				"title": "Téma",
				"examples": [
					"https://data.mvcr.gov.cz/zdroj/číselníky/témata-událostí/položky/umění-a-kultura"
				]
			}
		},
		"bezbariérovost": {
			"$ref": "https://ofn.gov.cz/bezbariérovost/draft/schémata/bezbariérovost.json"
		},
		"doba_trvání": {
			"$ref": "https://ofn.gov.cz/časová-specifikace/draft/schémata/seznam-časových-specifikací.json"
		},
		"vstupné": {
			"$ref": "https://ofn.gov.cz/vstupné/draft/schémata/více-vstupných.json"
		},
		"kontakt": {
			"type": "array",
			"items": {
				"$ref": "https://ofn.gov.cz/kontakty/draft/schémata/kontakt.json"
			}
		},
		"dílčí_událost": {
			"$ref": "https://ofn.gov.cz/události/draft/schémata/události.json"
		},
		"zaštiťující_událost": {
			"$ref": "https://ofn.gov.cz/události/draft/schémata/události.json"
		}
	}
}

=== MichalMed/otevrene-formalni-normy/události/draft/příklady/1.json
{
    "iri": "https://data.brno.cz/zdroj/události/2019/vinobraní",
    "název": {
        "cs": "Brněnské vinobraní",
        "en": "Brno Wine Festival"
    },
    "popis": {
        "cs": "Město Brno Vás zve na již 21. vinobraní.",
        "en": "City of Brno invites you to 21th Wine Festival."
    },
    "pořadatel": [{
        "osoba": {
            "ičo": "44992785",
            "název": "Statutární město Brno"
        }
    }],
    "umístění": [{
        "geometrie": {
            "type": "Point",
            "coordinates": [15.9915114, 48.8566829]
        },
        "adresa": {
            "adresní_místo": "https://linked.cuzk.cz/resource/ruian/adresni-misto/16135661"
        }
    }],
    "doba_trvání": [{
        "časový_interval": {
            "začátek": {
                "datum_a_čas": "2019-01-01T09:30:00+02:00"
            },
            "konec": {
                "datum_a_čas": "2019-01-07T18:00:00+02:00"
            }
        }},{
        "časový_interval": {
            "začátek": {
                "datum_a_čas": "2019-01-14T09:30:00+02:00"
            },
            "konec": {
                "datum_a_čas": "2019-01-20T18:00:00+02:00"
            }
        }
    }]
}
