=== MichalMed/otevrene-formalni-normy/bezbariérovost/draft/schémata/bezbariérovost.json
{
      "$schema": "http://json-schema.org/draft-07/schema",
      "$id": "https://ofn.gov.cz/bezbariérovost/draft/schémata/bezbariérovost.json",
      "type": "object",
      "readOnly": false,
      "writeOnly": false,
      "minProperties": 0,
      "title": "The Root Schema",
      "description": "The root schema comprises the entire JSON document.",
      "additionalProperties": true,
      "properties": {
          "popis": {
            "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
          },
          "fotografie": {
            "type": "array",
            "items": {
                "$id": "#/items/properties/fotografie/items",
                "type": "string",
                "format": "iri",
                "title": "Fotografie",
                "examples": [
                  "https://www.vozejkmap.cz/83465-verejny-zachody-pro-vozickare"
                  ]
            }
        },
          "datum_mapování": {
                    "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
          },
          "mapující_subjekt": {
            "type": "array",
            "items": {
                "$ref": "https://ofn.gov.cz/lidé-a-osoby/draft/schémata/člověk-či-osoba.json"
            }
        },
        "mapování_dle_metodiky": {
            "$id": "#/properties/mapovani_dle_metodiky",
            "type": "boolean",
            "tittle": "Mapování dle metodiky kategorizace objektů",
            "examples": true
          },               
          "přístupnost_děti_s_doprovodem": {
            "type": "array",
            "items": {
                "id": "#/properties/přístupnost_děti_s_doprovodem/items/přístupnost_děti_s_doprovodem",
                "type": "string",
                "format": "iri",
                "title": "Přístupnost pro děti s doprovodem",
                "examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
            }
          },
          "přístupnost_senioři": {
            "type": "array",
            "items": {
                "id": "#/properties/přístupnost_senioři/items/přístupnost_senioři",
                "type": "string",
                "format": "iri",
                "title": "Přístupnost pro seniory",
                "examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
            }
          },
          "tělesně_postižení_toaleta_přístupnost": {
            "type": "array",
            "items": {
                "id": "#/properties/tělesně_postižení_toaleta_přístupnost/items/tělesně_postižení_toaleta_přístupnost",
                "type": "string",
                "format": "iri",
                "title": "Přístupnost toalety pro tělesně postižené",
                "examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
            }
          },
          "tělesně_postižení_objekt_přístupnost": {
            "type": "array",
            "items": {
                "id": "#/properties/tělesně_postižení_objekt_přístupnost/items/tělesně_postižení_objekt_přístupnost",
                "type": "string",
                "format": "iri",
                "title": "Přístupnost objektu pro tělesně postižené",
                "examples": ["https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"]
            }
          },
          "objekt_vyhrazené_parkování": {
              "$id": "#/properties/objekt_vyhrazené_parkování",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Objekt_vyhrazené_parkování Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "objekt_obtížný_povrch": {
              "$id": "#/properties/objekt_obtížný_povrch",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Objekt_obtížný_povrch Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "objekt_obtížný_sklon": {
              "$id": "#/properties/objekt_obtížný_sklon",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Objekt_obtížný_sklon Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "vstup_hlavní_vchod": {
              "$id": "#/properties/vstup_hlavní_vchod",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_hlavní_vchod Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "vstup_hlavní_schody": {
              "$id": "#/properties/vstup_hlavní_schody",
              "type": "integer",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_hlavní_schody Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": 0,
              "examples": [
                  18
              ]
          },
          "vstup_hlavní_nájezd": {
              "$id": "#/properties/vstup_hlavní_nájezd",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_hlavní_nájezd Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "vstup_hlavní_plošina": {
              "$id": "#/properties/vstup_hlavní_plošina",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_hlavní_plošina Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "vstup_hlavní_výtah": {
              "$id": "#/properties/vstup_hlavní_výtah",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_hlavní_výtah Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "vstup_hlavní_výtah_sedátko": {
              "$id": "#/properties/vstup_hlavní_výtah_sedátko",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_hlavní_výtah_sedátko Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "vstup_hlavní_výtah_madlo": {
              "$id": "#/properties/vstup_hlavní_výtah_madlo",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_hlavní_výtah_madlo Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "vstup_hlavní_šířka_dveří": {
            "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
          },
          "vstup_vedlejší_vchod": {
              "$id": "#/properties/vstup_vedlejší_vchod",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_vedlejší_vchod Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "vstup_vedlejší_schody": {
              "$id": "#/properties/vstup_vedlejší_schody",
              "type": "integer",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_vedlejší_schody Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": 0,
              "examples": [
                  0
              ]
          },
          "vstup_vedlejší_nájezd": {
              "$id": "#/properties/vstup_vedlejší_nájezd",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_vedlejší_nájezd Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "vstup_vedlejší_plošina": {
              "$id": "#/properties/vstup_vedlejší_plošina",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_vedlejší_plošina Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "vstup_vedlejší_výtah": {
              "$id": "#/properties/vstup_vedlejší_výtah",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_vedlejší_výtah Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "vstup_vedlejší_výtah_sedátko": {
              "$id": "#/properties/vstup_vedlejší_výtah_sedátko",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_vedlejší_výtah_sedátko Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "vstup_vedlejší_výtah_madlo": {
              "$id": "#/properties/vstup_vedlejší_výtah_madlo",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Vstup_vedlejší_výtah_madlo Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "vstup_vedlejší_šířka_dveří": {
              "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
          },
          "interiér_schody": {
              "$id": "#/properties/interiér_schody",
              "type": "integer",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Interiér_schody Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": 0,
              "examples": [
                  5
              ]
          },
          "interiér_minimální_průchod": {
              "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
          },
          "interiér_výška_prahu": {
              "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
          },
          "interiér_přístupnost": {
              "$id": "#/properties/interiér_přístupnost",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Interiér_přístupnost Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "interiér_nájezd": {
              "$id": "#/properties/interiér_nájezd",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Interiér_nájezd Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "interiér_plošina": {
              "$id": "#/properties/interiér_plošina",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Interiér_plošina Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "interiér_výtah": {
              "$id": "#/properties/interiér_výtah",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Interiér_výtah Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "interiér_výtah_sedátko": {
              "$id": "#/properties/interiér_výtah_sedátko",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Interiér_výtah_sedátko Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "interiér_výtah_madlo": {
              "$id": "#/properties/interiér_výtah_madlo",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Interiér_výtah_madlo Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "interiér_točité_schodiště": {
              "$id": "#/properties/interiér_točité_schodiště",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Interiér_točité_schodiště Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "toaleta_šířka_dveří": {
              "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
          },
          "toaleta_klíč": {
              "$id": "#/properties/toaleta_klíč",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Toaleta_klíč Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "toaleta_euroklíč": {
              "$id": "#/properties/toaleta_euroklíč",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Toaleta_euroklíč Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "toaleta_dostatečný_rozměr": {
              "$id": "#/properties/toaleta_dostatečný_rozměr",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Toaleta_dostatečný_rozměr Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "toaleta_signalizační_tlačítko": {
              "$id": "#/properties/toaleta_signalizační_tlačítko",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Toaleta_signalizační_tlačítko Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "toaleta_wc_boční_přístup": {
              "$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/množství.json"
          },
          "toaleta_wc_výška_sedátka": {
              "$id": "#/properties/toaleta_wc_výška_sedátka",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Toaleta_wc_výška_sedátka Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "toaleta_wc_madlo": {
              "$id": "#/properties/toaleta_wc_madlo",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Toaleta_wc_madlo Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "toaleta_umyvadlo_dostatečný_prostor": {
              "$id": "#/properties/toaleta_umyvadlo_dostatečný_prostor",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Toaleta_umyvadlo_dostatečný_prostor Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  true
              ]
          },
          "toaleta_přebalovací_pult": {
              "$id": "#/properties/toaleta_přebalovací_pult",
              "type": "boolean",
              "readOnly": false,
              "writeOnly": false,
              "title": "The Toaleta_přebalovací_pult Schema",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                  false
              ]
          },
          "braillové_písmo": {
              "$id": "#/properties/braillové_písmo",
              "type": "boolean",
              "title": "Braillové písmo",
              "examples": true
          },
          "hlasový_asistent": {
              "$id": "#/properties/hlasový_asistent",
              "type": "boolean",
              "tittle": "Hlasový asistent",
              "examples": true
          },
          "vodící_linie": {
              "$id": "#/propertie/vodící_linie",
              "type": "boolean",
              "tittle": "Vodící linie",
              "examples": true
          },
          "vodící_pes": {
                "$id": "#/properties/vodící_pes",
                "type": "boolean",
                "tittle": "Vodící pes",
                "examples": true
          } 
      }
  }

=== MichalMed/otevrene-formalni-normy/bezbariérovost/draft/příklady/1.json
{
  "popis": {
    "cs": "Vstup do budovy a základní orientace: Škola se nachází ve starší zástavbě a skládá se z několika, na sebe navazujících budov, propojených dvorem. Na dvůr navazuje zahrada a kolej pro studenty. Pro náš pohyb po celém objektu budou důležité dva na sebe kolmé směry. Hlavní orientace, to je ulice, kterou jste přišli se školou po pravé straně. V objektu je tento směr totožný se vstupem do velké auly, chodbami v hlavní budově a osami obou schodišť. Toto je pro další orientaci hlavní směr pohledu nebo chůze (dále jen HS). Směr zády kolmo k ulici bude vedlejší směr (dále bude označován jen VS). To je pohled na dům – hlavní vstupní chodba, navazující dvůr, zahrada a domov pro studenty. Stejným směrem je orientována malá aula v přízemí a propojovací chodba ve třetím patře. Budovy budou popisovány odděleně a pro zpřesnění bude vždy v daném odstavci uveden směr pohledu, od něhož je další popis odvozen. Symboly HS a VS budou uvedeny v závorkách. Malá aula a spojovací chodba ve třetím patře bude popsána v obou směrech."
  },
  "datum_mapování": {
      "datum_a_čas": "2019-09-27T09:30:00"
  },
  "mapující_subjekt": [{
    "osoba": {
      "ičo": "44992785",
      "název": "Město Brno"
      }
  }],
  "fotografie": [
    "https://www.mpb.cz/osoby-s-handicapem/informacni-hlasove-majacky-pro-nevidome/"
  ],
  "braillové_písmo": true,
  "hlasový_asistent": true,
  "vodící_linie": true,
  "vodící_pes": true
}

=== MichalMed/otevrene-formalni-normy/bezbariérovost/draft/příklady/2.json
{
  "popis": {
    "cs": "Hrad nabízí stálé i příležitostné muzejní expozice včetně kasemat. Z vyhlídkového ochozu se nabízí ojedinělý pohled na město Brno a jeho okolí. Po telefonické domluvě možnost parkování v areálu hradu. Bezbariérový vstup do hradu je bočními dveřmi středního křídla (vpravo), asistence zajistí mobilní nájezd. Bezbariérové WC ve všech patrech.",
    "en": "The castle offers permanent and occasional museum exhibits including casemates. There is a unique view around the Brno and its surroundings from the observation deck. Parking in the castle is possible after calling the reception. Barrier-free entrance to the castle is located in the middle wing of the castle (right). Assistance will ensure a mobile entrance. Barrier-free toilets are on all floors."
  },
  "datum_mapování": {
      "datum_a_čas": "2019-09-27T09:30:00"
  },
  "mapující_subjekt": [{
    "osoba": {
      "ičo": "44992785",
      "název": "Město Brno"
      }
  }],
  "mapování_dle_metodiky": false,
  "fotografie": [
    "https://www.vozejkmap.cz/83465-verejny-zachody-pro-vozickare"
  ],
  "tělesně_postižení_toaleta_přístupnost": [
    "https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"
  ],
  "tělesně_postižení_objekt_přístupnost": [
    "https://data.mvcr.gov.cz/zdroj/číselníky/stupně-přístupnosti/položky/přístupný"
  ],
  "objekt_vyhrazené_parkování": true,
  "vstup_hlavní_nájezd": false,
  "vstup_hlavní_plošina": false,
  "vstup_hlavní_výtah": true
}
