=== MichalMed/otevrene-formalni-normy/úřední-desky/draft/schémata/úřední-deska.xsd
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:deska="https://data.gov.cz/otevřené-formální-normy/úřední-desky/"
	xmlns:adresa="https://data.gov.cz/otevřené-formální-normy/adresy/"
	targetNamespace="https://data.gov.cz/otevřené-formální-normy/úřední-desky/"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">

	<xs:import
		namespace="https://data.gov.cz/otevřené-formální-normy/adresy/"
		schemaLocation="https://data.gov.cz/otevřené-formální-normy/adresy/draft/schémata/adresa.xsd"/>

	<xs:complexType name="úřední_deska">
		<xs:sequence maxOccurs="unbounded">
            <xs:element name="url" type="xs:string" minOccurs="0"/>
            <xs:element name="organizace" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="název" type="xs:string" minOccurs="0"/>
                        <xs:element name="ičo" type="xs:string" minOccurs="0"/>
                        <xs:element name="adresa" type="adresa:adresa" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:any namespace="##other" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
			<xs:element name="oznámení" type="deska:oznámení"/>
            <xs:any namespace="##other" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="oznámení">
		<xs:sequence>
			<xs:element name="identifikátor" type="xs:string" minOccurs="0"/>
			<xs:element name="autor" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="název" type="xs:string" minOccurs="0"/>
						<xs:any namespace="##other" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="url" type="xs:string" minOccurs="0"/>
			<xs:element name="název" type="xs:string"/>
			<xs:element name="anotace" type="xs:string" minOccurs="0"/>
			<xs:element name="zveřejněno" type="xs:date" minOccurs="0"/>
			<xs:element name="zveřejněno_čas" type="xs:time" minOccurs="0"/>
			<xs:element name="sejmuto" type="xs:date" minOccurs="0"/>
			<xs:element name="sejmuto_čas" type="xs:time" minOccurs="0"/>
			<xs:element name="schváleno" type="xs:date" minOccurs="0"/>
			<xs:element name="schváleno_čas" type="xs:time" minOccurs="0"/>
			<xs:element name="značka" type="xs:string" minOccurs="0"/>
			<xs:element name="číslo_jednací" type="xs:string" minOccurs="0"/>
			<xs:element name="revize" type="xs:string" minOccurs="0"/>
			<xs:element name="agenda" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="název" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
			<xs:element name="dokument" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="0">
						<xs:element name="název" type="xs:string" minOccurs="0"/>
						<xs:element name="url" type="xs:string" minOccurs="0"/>
						<xs:any namespace="##other" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="subjekt" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="0">
						<xs:element name="název" type="xs:string" minOccurs="0"/>
						<xs:element name="adresa" type="adresa:adresa" minOccurs="0" maxOccurs="unbounded"/>
						<xs:any namespace="##other" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:any namespace="##other" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="úřední_deska" type="deska:úřední_deska"/>
</xs:schema>

=== MichalMed/otevrene-formalni-normy/úřední-desky/draft/příklady/3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<deska:úřední_deska
    xmlns="http://opendata.gov.cz/schema/xsd/typy/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:deska="https://data.gov.cz/otevřené-formální-normy/úřední-desky/"
    xsi:schemaLocation="https://data.gov.cz/otevřené-formální-normy/úřední-desky/
                        https://data.gov.cz/otevřené-formální-normy/úřední-desky/draft/schémata/úřední-deska.xsd"
    xmlns:x="https://příklad.cz"
    >
    <deska:url>https://example.com/uredni_deska/</deska:url>
    <deska:organizace>
        <deska:ičo>00258245</deska:ičo>
    </deska:organizace>
    <deska:oznámení>
        <deska:identifikátor>2018-13</deska:identifikátor>
        <deska:url>https://example.com/uredni_deska/2018-2</deska:url>
        <deska:název>Podpora spolkového života ve městě</deska:název>
        <deska:zveřejněno>2018-01-20</deska:zveřejněno>
        <deska:sejmuto>2018-02-20</deska:sejmuto>
    </deska:oznámení>
    <deska:oznámení>
        <deska:identifikátor>2018-14</deska:identifikátor>
        <deska:url>https://example.com/uredni_deska/2018-3</deska:url>
        <deska:název>Podpora spolkového života ve městě II</deska:název>
        <deska:zveřejněno>2018-03-20</deska:zveřejněno>
        <deska:sejmuto>2018-04-20</deska:sejmuto>
        <x:zveřejnil>Mirek Dušín</x:zveřejnil>
        <x:odbor>VD</x:odbor>
    </deska:oznámení>
</deska:úřední_deska>

=== MichalMed/otevrene-formalni-normy/úřední-desky/draft/příklady/1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<deska:úřední_deska
    xmlns="http://opendata.gov.cz/schema/xsd/typy/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:deska="https://ofn.gov.cz/úřední-desky/"
    xsi:schemaLocation="https://ofn.gov.cz/úřední-desky/
                        https://ofn.gov.cz/úřední-desky/draft/schémata/úřední-deska.xsd"
    >
    <deska:url>https://example.com/uredni_deska/</deska:url>
    <deska:provozovatel>
        <deska:ičo>00258245</deska:ičo>
    </deska:provozovatel>
    <deska:oznámení>
        <deska:identifikátor>2018-13</deska:identifikátor>
        <deska:url>https://example.com/uredni_deska/2018-2</deska:url>
        <deska:název>Podpora spolkového života ve městě</deska:název>
        <deska:zveřejněno>2018-01-20</deska:zveřejněno>
        <deska:sejmuto>2018-02-20</deska:sejmuto>
    </deska:oznámení>
</deska:úřední_deska>
