=== MichalMed/otevrene-formalni-normy/vstupné/draft/schémata/vstupné.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://ofn.gov.cz/vstupné/draft/schémata/vstupné.json",
	"type": "object",
	"title": "Vstupné",
	"properties": {
		"iri": {
			"$id": "#/properties/iri",
			"type": "string",
			"format": "iri",
			"title": "Identifikátor",
			"examples": [
				"https://www.trebic.cz/zdroj/aktualita/2020/dopadení-lupiče-na-francouzské-ulici"
			]
		},
		"název": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
		},
		"popis": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
		},
		"vytvořeno": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
		},
		"relevantní_do": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
		},
		"zneplatněno": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
		},
		"příloha": {
			"$ref": "https://ofn.gov.cz/přílohy/draft/schémata/přílohy.json"
		},
		"podmínka": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/text.json"
		},
		"platnost": {
			"$ref": "https://ofn.gov.cz/časová-specifikace/draft/schémata/časová-specifikace.json"
		},
		"částka": {
			"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/částka.json"
		}
	}
}

=== MichalMed/otevrene-formalni-normy/vstupné/draft/příklady/2.json
[{
    "název": {
        "cs": "Studentské vstupné"
    },
    "podmínka": {
        "cs": "Pro získání studentského vstupného je zapotřebí předložit kartu ISIC.\nStudent musí zároveň mít méně než 26."
    },
    "platnost": {
        "vznik_časové_platnosti": {
            "datum_a_čas": "2019-08-01T09:30:00+02:00"
        },
        "ukončení_časové_platnosti": {
            "datum_a_čas": "2019-08-07T18:00:00+02:00"
        }
    },
    "částka": {
            "výše": 289.90,
            "měna": "CZK"
    }

}]
